### ISSUE TITLE
Needs  pino-elasticsearch dependency when "Set up logging" is Yes

### ISSUE THREAD

**Issue by copongcopong** [flywheelsports/generator-fwsp-hydra#21]

**Comment by cjus** [comment]
@copongcopong Thanks for your feedback. We'll get back to you shortly.

**Comment by emadum** [comment]
Sorry about the delay in getting to this! pino-elasticsearch needs to be installed globally which is why I didn't just add it to the dependencies. I'm thinking perhaps adding a postinstall script to the generated package.json which just does `npm install --global pino-elasticsearch` is the best move.

@cjus thoughts?

**Comment by cjus** [comment]
@emadum updating the documentation for the generator would let users know that if they enable logging then the above install is necessary.

**Comment by emadum** [comment]
child_process.fork is now used instead of cross-spawn, meaning npm install --global pino-elasticsearch is no longer needed.
